-- 3. What is the total revenue generated by each salesperson?
-- 3. Qual a receita total produzida por cada funcionário?

-- Esta questão é complementar à questão número 2, pois permite atribuir o faturamento realizado por cada funcionário e identificar quais são aqueles mais retáveis para o nosso negócio, podendo assim incentivá-los a manter o bom desempenho e, com análises mais profundas, identificar as características dos funcionários mais rentáveis para possíveis novas contratações.
-- Também é importante para identificar funcionários com baixo desempenho e adotar medidas para se evitar tais problemas, utilizando-se de incentivos para que estes funcionários tenham melhores desempenhos.

SELECT
    sp.name
  , SUM(c.cost_$) AS total_revenue_by_salesperson
FROM
  salespersons AS sp
INNER JOIN
  sales AS s
  ON
    sp.salesman_id = s.salesman_id
INNER JOIN
  cars AS c
  ON
    c.car_id = s.car_id
GROUP BY
  sp.name
ORDER BY
  sp.name;
