-- 5. What is the total revenue generated by each car type?
-- 5. Qual é a receita total produzida pela venda de cada tipo de carro? 

-- Esta questão permite que encontremos os carros responsáveis pelas maiores e menores receitas do ano de 2022. Isto permite encontrar aqueles que são mais lucrativos e realizar abastecimento de estoques de maneira mais estratégica.

SELECT
    c.car_id
  , c.type
  , SUM(c.cost_$) AS total_revenue_by_car
FROM
  cars AS c
INNER JOIN
  sales AS s
  ON
    s.car_id = c.car_id
GROUP BY
  s.car_id
ORDER BY
  c.car_id;
