-- 7. What is the total revenue generated by the sales of hatchback cars?
-- 7. Qual a receita total produzida pela venda de carros com porta-malas grande?

-- Esta questão permite observar o faturamento de um determinado produto, se ele é satisfatório ou se a venda do produto deve ser descontinuada.

SELECT
     c.style
   , SUM(c.cost_$) AS total_revenue
FROM
   cars AS c
INNER JOIN
   sales AS s
   ON
     c.car_id = s.car_id
WHERE
   style = 'Hatchback';
