-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
-- 8. Qual a receita total produzida pela venda de carros SUV no ano de 2022?

-- Esta questão permite observar o faturamento de um determinado produto ao longo de um ano específico, se ele é satisfatório ou se a venda do produto deve ser descontinuada.

SELECT
    c.style
  , SUM(c.cost_$) AS total_revenue
FROM
  cars AS c
INNER JOIN
  sales AS s
  ON
    c.car_id = s.car_id
WHERE
  c.style = 'SUV'
  AND
  YEAR(s.purchase_date) = '2022'
